"use client"
import { useEffect, useState } from "react"
import { BrainCircuit, Copy, Check, ShieldCheck, Sparkles, FileText } from "lucide-react"
import { toast } from "sonner"

interface DeveloperDossierProps {
  username: string
  skills: string[]
  topRepos: string[]
}

export function DeveloperDossier({ username, skills, topRepos }: DeveloperDossierProps) {
  const [dossier, setDossier] = useState<string>("")
  const [loading, setLoading] = useState(true)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL || "/api"}/ai/developer-dossier`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username, skills, top_repos: topRepos })
    })
      .then(r => r.json())
      .then(d => setDossier(d.dossier || ""))
      .catch(() => setDossier("Unable to generate dossier at this moment."))
      .finally(() => setLoading(false))
  }, [username, skills, topRepos])

  const handleCopy = () => {
    if (!dossier) return
    navigator.clipboard.writeText(`[Project Ronin Developer Dossier: @${username}]\n\n${dossier}`)
    setCopied(true)
    toast("📋 Copied developer intelligence report")
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExport = () => {
    if (!dossier) return;
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast("Please allow popups to export the dossier card");
      return;
    }
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Project Ronin — Developer Dossier (@${username})</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; background: #0d1117; color: #e6edf3; max-width: 800px; margin: 0 auto; line-height: 1.6; }
            .badge { display: inline-block; background: #238636; color: white; padding: 4px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }
            .header { border-bottom: 2px solid #30363d; padding-bottom: 16px; margin-bottom: 24px; }
            h1 { margin: 0 0 8px; color: #58a6ff; font-size: 24px; }
            .skills { margin-top: 20px; display: flex; gap: 8px; flex-wrap: wrap; }
            .skill { background: #1f3d5c; color: #58a6ff; border: 1px solid #1f4f7c; padding: 4px 10px; border-radius: 6px; font-size: 12px; }
            .meta { font-size: 13px; color: #8b949e; margin-top: 30px; border-top: 1px solid #30363d; padding-top: 12px; }
            @media print { body { background: white; color: black; } h1 { color: #0969da; } .skill { border-color: #d0d7de; background: #f6f8fa; color: #24292f; } }
          </style>
        </head>
        <body>
          <div class="header">
            <span class="badge">⚔️ Verified Ronin Builder</span>
            <h1>Developer Intelligence Dossier: @${username}</h1>
            <p style="color: #8b949e; margin: 0;">Synthesized by Gemini AI & Dual-Brain Architecture</p>
          </div>
          <div style="font-size: 15px; white-space: pre-wrap;">${dossier}</div>
          ${skills && skills.length ? `<div class="skills"><strong>Core Stack:</strong> ${skills.map(s => `<span class="skill">${s}</span>`).join(" ")}</div>` : ""}
          <div class="meta">Generated by Project Ronin • Social Intelligence Layer for Open-Source</div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
    toast("📄 Generated resume dossier print sheet");
  };

  return (
    <div className="p-5 bg-gh-surface border border-gh-border rounded-xl flex flex-col gap-4 relative overflow-hidden shadow-lg">
      <div className="flex items-center justify-between border-b border-gh-border/70 pb-3 flex-wrap gap-2 select-none">
        <div className="flex items-center gap-2">
          <BrainCircuit className="w-5 h-5 text-gh-purple animate-pulse" />
          <h3 className="text-sm font-bold text-white tracking-tight">
            Developer Intelligence Dossier
          </h3>
          <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded-full bg-gh-purple/10 text-gh-purple border border-gh-purple/30">
            ✦ Dual-Brain AI
          </span>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 text-[11px] text-gh-green font-medium bg-gh-green/10 px-2 py-0.5 rounded-md border border-gh-green/20">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Verified Builder</span>
          </div>
          <button
            onClick={handleExport}
            disabled={loading || !dossier}
            className="flex items-center gap-1 text-xs text-purple-300 hover:text-white px-2 py-1 rounded bg-purple-950/40 border border-purple-800/60 hover:bg-purple-900/50 transition-colors cursor-pointer disabled:opacity-40"
            title="Export dossier card for resumes (Requested in User Survey)"
          >
            <FileText className="w-3.5 h-3.5 text-purple-400" />
            <span>Export Resume</span>
          </button>
          <button
            onClick={handleCopy}
            disabled={loading || !dossier}
            className="flex items-center gap-1 text-xs text-gh-muted hover:text-white px-2 py-1 rounded bg-[#161b22] border border-gh-border transition-colors cursor-pointer disabled:opacity-40"
            title="Copy dossier to clipboard"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-gh-green" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? "Copied" : "Copy"}</span>
          </button>
        </div>
      </div>

      {loading ? (
        <div className="space-y-3 py-2">
          <div className="flex items-center gap-2 text-xs text-gh-muted">
            <Sparkles className="w-3.5 h-3.5 text-gh-purple animate-spin" />
            <span>Synthesizing repository contributions and architecture patterns...</span>
          </div>
          <div className="h-3 bg-[#21262d] rounded animate-pulse w-full" />
          <div className="h-3 bg-[#21262d] rounded animate-pulse w-11/12" />
          <div className="h-3 bg-[#21262d] rounded animate-pulse w-4/5" />
          <div className="h-3 bg-[#21262d] rounded animate-pulse w-full mt-3" />
          <div className="h-3 bg-[#21262d] rounded animate-pulse w-9/12" />
        </div>
      ) : (
        <div className="flex flex-col gap-4 leading-relaxed">
          <p className="text-xs sm:text-sm text-neutral-300 whitespace-pre-wrap leading-relaxed">
            {dossier}
          </p>

          {skills && skills.length > 0 && (
            <div className="flex items-center gap-2 flex-wrap pt-2 border-t border-gh-border/50 text-[11px] text-gh-muted">
              <span className="font-semibold text-white">Analyzed Core Stack:</span>
              {skills.slice(0, 5).map(skill => (
                <span key={skill} className="px-2 py-0.5 rounded bg-[#1f3d5c] text-gh-blue border border-[#1f4f7c]">
                  {skill}
                </span>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

